# Generated by Django 3.0.6 on 2020-06-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='description',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='profile_picture',
            field=models.ImageField(default='defaultProfilePicture.png', upload_to='profile_pics'),
        ),
    ]
