# Generated by Django 3.0.6 on 2020-06-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200617_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='description',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
