# Generated by Django 3.0.6 on 2020-06-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20200620_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='full_name',
            field=models.CharField(blank=True, default='unspecified', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/defaultProfilePicture.png', upload_to='profile_pics'),
        ),
    ]
